### ISSUE TITLE
Crash if SSL unavailable

### ISSUE THREAD

**Issue by d4rken** [piwik/piwik-sdk-android#180]
* NVIDIA BP 1@ 4.4.4
* Build KTU84Q PrivatOS 1.1.17

```
java.lang.IllegalArgumentException: protocol SSLv3 is not supported
        at com.android.org.conscrypt.NativeCrypto.checkEnabledProtocols(NativeCrypto.java:852)
        at com.android.org.conscrypt.OpenSSLSocketImpl.setEnabledProtocols(OpenSSLSocketImpl.java:806)
        at com.android.okhttp.internal.Platform.supportTlsIntolerantServer(Platform.java:75)
        at com.android.okhttp.Connection.upgradeToTls(Connection.java:137)
        at com.android.okhttp.Connection.connect(Connection.java:107)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
        at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
        at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:136)
        at org.piwik.sdk.a.b.a(Dispatcher.java:256)
        at org.piwik.sdk.a.b$1.run(Dispatcher.java:167)
        at java.lang.Thread.run(Thread.java:841)
```

**Comment by d4rken** [comment]
`implementation 'org.piwik.sdk:piwik-sdk:2.0.0'`

**Comment by d4rken** [comment]
Nvm, already fixed in `dev`.

https://github.com/piwik/piwik-sdk-android/blob/dev/piwik-sdk/src/main/java/org/piwik/sdk/dispatcher/DefaultPacketSender.java#L57
